---
- name: Setup dynamic role
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  gather_facts: false
  connection: ssh
  vars:
    region: eu-west-1
    keypair: 20170831
  tasks:
    - name: Add role "{{ the_role }}"
      include: roles/project.{{ the_role }}/tasks/main.yml
