---
- name: Copy Supervisor init file into place 
  template:
    src: roles/project.supervisor/templates/supervisord.init.j2
    dest: /etc/init.d/supervisord
    owner: root
    group: root
    mode: 0755
  notify: restart supervisor
