---
- name: Include variables.
  include_vars: roles/project.supervisor/defaults/main.yml

- name: Ensure Supervisor is installed (specific version).
  apt:
    name: supervisor={{ supervisor_version }}
    state: present
  when: supervisor_version != 'latest'

- name: Ensure Supervisor is installed (latest version).
  apt:
    name: supervisor
    state: latest
  when: supervisor_version == 'latest'

- name: Ensure Supervisor log dir exists.
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755

- include: config.yml

- include: init-setup.yml
  when: supervisor_started or supervisor_enabled

- name: Ensure Supervisor is started (if configured).
  service:
    name: supervisor
    state: started
  when: supervisor_started

- name: Ensure Supervisor is enabled at boot (if configured).
  service:
    name: supervisor
    enabled: yes
  when: supervisor_enabled
