---
ntp_enabled: true
ntp_timezone: Etc/UTC

ntp_manage_config: false

ntp_area: ''
ntp_daemon: ntp
ntp_servers:
  - "0{{ ntp_area }}.pool.ntp.org iburst"
  - "1{{ ntp_area }}.pool.ntp.org iburst"
  - "2{{ ntp_area }}.pool.ntp.org iburst"
  - "3{{ ntp_area }}.pool.ntp.org iburst"

ntp_restrict:
  - "127.0.0.1"
  - "::1"
